# 04 - Submission And Report

**Goal:** Finalize trained artifacts for submission and report writing.

**What you will learn:** How to validate exported packages, create the final zip, load eval summaries, rebuild plots, and gather report facts.

**Inputs:** Exported agent packages from the full pipeline notebook.

**Outputs:** Validation results, final `TEAMNAME_AGENT.zip`, evaluation summary tables, and report-ready artifact paths.

**Success criteria:** The chosen package imports, `act()` works, the zip has the expected top-level folder, and readiness summary is true.

In [30]:
from pathlib import Path
import importlib
import os
import sys

PROJECT_MARKER = Path("soccer_twos_project") / "notebook_tools.py"


def _running_in_colab():
    if "google.colab" in sys.modules:
        return True
    if os.environ.get("COLAB_RELEASE_TAG") or os.environ.get("COLAB_GPU"):
        return True
    try:
        import google.colab  # type: ignore  # noqa: F401
        return True
    except Exception:
        return False


def _candidate_project_roots():
    seen = set()

    def add(path):
        path = Path(path).expanduser()
        key = str(path)
        if key not in seen:
            seen.add(key)
            yield path

    for env_name in ("SOCCER_TWOS_PROJECT_ROOT", "PROJECT_ROOT"):
        value = os.environ.get(env_name)
        if value:
            yield from add(value)

    cwd = Path.cwd().resolve()
    for base in (cwd, *cwd.parents):
        yield from add(base)
        yield from add(base / "soccer-twos-starter")
        yield from add(base / "project" / "soccer-twos-starter")

    if sys.platform == "darwin":
        yield from add(
            Path.home()
            / "all_data"
            / "Georgia Tech"
            / "Course Content"
            / "CS 8803- DRL"
            / "project"
            / "soccer-twos-starter"
        )

    if _running_in_colab():
        try:
            from google.colab import drive  # type: ignore
            if not Path("/content/drive/MyDrive").exists():
                drive.mount("/content/drive")
        except Exception:
            pass
        for drive_root in (Path("/content/drive/MyDrive"), Path("/content/drive/Shareddrives"), Path("/content")):
            for relative in (
                Path("CS 8803- DRL") / "project" / "soccer-twos-starter",
                Path("project") / "soccer-twos-starter",
                Path("soccer-twos-starter"),
                Path("Colab Notebooks") / "soccer-twos-starter",
            ):
                yield from add(drive_root / relative)


def _find_project_root():
    for candidate in _candidate_project_roots():
        if (candidate / PROJECT_MARKER).exists():
            return candidate.resolve()
    raise FileNotFoundError(
        "Could not find soccer_twos_project/notebook_tools.py. "
        "Open this notebook from the project root/notebooks folder, or set SOCCER_TWOS_PROJECT_ROOT."
    )


PROJECT_ROOT = _find_project_root()
os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

for _module_name in list(sys.modules):
    if _module_name == "soccer_twos_project" or _module_name.startswith("soccer_twos_project."):
        del sys.modules[_module_name]

importlib.invalidate_caches()
from IPython.display import Markdown, display
from soccer_twos_project.notebook_tools import *

ctx = setup_project()
show_hardware()

Runtime: linux
Project root: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter
Artifact root: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos
Python: /coc/scratch/dgarg/miniconda3/envs/soccertwos/bin/python
soccer_twos: /coc/scratch/dgarg/miniconda3/envs/soccertwos/lib/python3.8/site-packages/soccer_twos/__init__.py
ray: 1.13.0
torch: 1.8.1+cu111
python: /coc/scratch/dgarg/miniconda3/envs/soccertwos/bin/python
{
  "cpu_count": 128,
  "gpu_name": "NVIDIA A40",
  "mlx_available": false,
  "ram_gb": 503.69,
  "torch_cuda_available": true,
  "torch_cuda_device_count": 8,
  "torch_cuda_device_names": [
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40",
    "NVIDIA A40"
  ],
  "torch_cuda_runtime_probe_device": "NVIDIA A40",
  "torch_cuda_runtime_probe_error": "",
  "torch_cuda_runtime_ready": true,
  "torch_cuda_version": "11.1",
  "torch_mps_available": false,
  "torch_version": "1.8.1+cu111"
}

## Configuration

Replace `TEAMNAME_AGENT` with your real submission folder name before the final upload.

In [40]:
CANDIDATE_AGENTS = ["soccer_ppo_baseline", "soccer_ppo_shaped", "soccer_ppo_curriculum", "soccer_ppo_curriculum_v3", "soccer_bc_imitation"]
SOURCE_AGENT = "soccer_ppo_curriculum_v3"
TEAM_AGENT_NAME = "TEAMNAME_v3_AGENT"
RUN_FINAL_EVALS = False
CREATE_FINAL_ZIP = True

## Artifact Checklist

This shows which folders already contain checkpoints, plots, submissions, and eval files.

In [41]:
artifact_checklist(ctx)

{
  "checkpoints": {
    "examples": [
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.pkl",
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.txt",
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/events.out.tfevents.1776930613.jayne.cc.gatech.edu",
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.json",
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.pkl",
      "soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/result.json",
      "soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/.is_checkpoint",
      "soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10",
      "soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10.tune_metadata",
      "soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000020/.is_checkpoint"
    ],
    "file_count": 256,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/checkpoints"
  },
  "datasets": {
    "examples": [
      "bc_expert_dataset.npz"
    ],
    "file_count": 1,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/datasets"
  },
  "evals": {
    "examples": [
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_episodes.csv",
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_summary.json",
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_v2_episodes.csv",
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_v2_summary.json",
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_v3_episodes.csv",
      "soccer_ppo_baseline_vs_soccer_ppo_curriculum_v3_summary.json",
      "soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v2_episodes.csv",
      "soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v2_summary.json",
      "soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v3_episodes.csv",
      "soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v3_summary.json"
    ],
    "file_count": 10,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/evals"
  },
  "logs": {
    "examples": [],
    "file_count": 0,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/logs"
  },
  "plots": {
    "examples": [
      "learning_curve_comparison.png",
      "soccer_ppo_baseline__PPO_Soccer_2bb93_00000_0_2026-04-21_14-51-56.png",
      "soccer_ppo_baseline__PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41.png",
      "soccer_ppo_baseline__PPO_Soccer_79595_00000_0_2026-04-23_08-32-21.png",
      "soccer_ppo_baseline__PPO_Soccer_87dbd_00000_0_2026-04-23_08-18-26.png",
      "soccer_ppo_baseline__PPO_Soccer_a18e9_00000_0_2026-04-21_14-48-05.png",
      "soccer_ppo_baseline__PPO_Soccer_dac60_00000_0_2026-04-21_18-38-45.png",
      "soccer_ppo_curriculum__PPO_Soccer_8ce04_00000_0_2026-04-23_09-08-41.png",
      "soccer_ppo_curriculum_v2__PPO_Soccer_dca3b_00000_0_2026-04-23_16-13-15.png",
      "soccer_ppo_curriculum_v3__PPO_Soccer_0b1b1_00000_0_2026-04-23_18-09-05.png"
    ],
    "file_count": 11,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots"
  },
  "root": {
    "examples": [
      ".DS_Store",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.pkl",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.txt",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/events.out.tfevents.1776930613.jayne.cc.gatech.edu",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.json",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.pkl",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/result.json",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/.is_checkpoint",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10",
      "checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10.tune_metadata"
    ],
    "file_count": 397,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos"
  },
  "submissions": {
    "examples": [
      "TEAMNAME_AGENT/README.md",
      "TEAMNAME_AGENT/__init__.py",
      "TEAMNAME_AGENT/__pycache__/__init__.cpython-38.pyc",
      "TEAMNAME_AGENT/__pycache__/agent.cpython-38.pyc",
      "TEAMNAME_AGENT/__pycache__/model.cpython-38.pyc",
      "TEAMNAME_AGENT/agent.py",
      "TEAMNAME_AGENT/checkpoint.pth",
      "TEAMNAME_AGENT/metadata.json",
      "TEAMNAME_AGENT/model.py",
      "TEAMNAME_AGENT/requirements.txt"
    ],
    "file_count": 118,
    "path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions"
  }
}

{'root': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos',
  'file_count': 397,
  'examples': ['.DS_Store',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.pkl',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.txt',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/events.out.tfevents.1776930613.jayne.cc.gatech.edu',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.json',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.pkl',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/result.json',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/.is_checkpoint',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10',
   'checkpoints/soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10.tune_metadata']},
 'checkpoints': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/checkpoints',
  'file_count': 256,
  'examples': ['soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.pkl',
   'soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/error.txt',
   'soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/events.out.tfevents.1776930613.jayne.cc.gatech.edu',
   'soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.json',
   'soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/params.pkl',
   'soccer_ppo_baseline/PPO_Soccer_0f821_00000_0_2026-04-23_03-50-13/result.json',
   'soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/.is_checkpoint',
   'soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10',
   'soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000010/checkpoint-10.tune_metadata',
   'soccer_ppo_baseline/PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41/checkpoint_000020/.is_checkpoint']},
 'plots': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots',
  'file_count': 11,
  'examples': ['learning_curve_comparison.png',
   'soccer_ppo_baseline__PPO_Soccer_2bb93_00000_0_2026-04-21_14-51-56.png',
   'soccer_ppo_baseline__PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41.png',
   'soccer_ppo_baseline__PPO_Soccer_79595_00000_0_2026-04-23_08-32-21.png',
   'soccer_ppo_baseline__PPO_Soccer_87dbd_00000_0_2026-04-23_08-18-26.png',
   'soccer_ppo_baseline__PPO_Soccer_a18e9_00000_0_2026-04-21_14-48-05.png',
   'soccer_ppo_baseline__PPO_Soccer_dac60_00000_0_2026-04-21_18-38-45.png',
   'soccer_ppo_curriculum__PPO_Soccer_8ce04_00000_0_2026-04-23_09-08-41.png',
   'soccer_ppo_curriculum_v2__PPO_Soccer_dca3b_00000_0_2026-04-23_16-13-15.png',
   'soccer_ppo_curriculum_v3__PPO_Soccer_0b1b1_00000_0_2026-04-23_18-09-05.png']},
 'datasets': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/datasets',
  'file_count': 1,
  'examples': ['bc_expert_dataset.npz']},
 'submissions': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions',
  'file_count': 118,
  'examples': ['TEAMNAME_AGENT/README.md',
   'TEAMNAME_AGENT/__init__.py',
   'TEAMNAME_AGENT/__pycache__/__init__.cpython-38.pyc',
   'TEAMNAME_AGENT/__pycache__/agent.cpython-38.pyc',
   'TEAMNAME_AGENT/__pycache__/model.cpython-38.pyc',
   'TEAMNAME_AGENT/agent.py',
   'TEAMNAME_AGENT/checkpoint.pth',
   'TEAMNAME_AGENT/metadata.json',
   'TEAMNAME_AGENT/model.py',
   'TEAMNAME_AGENT/requirements.txt']},
 'evals': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/evals',
  'file_count': 10,
  'examples': ['soccer_ppo_baseline_vs_soccer_ppo_curriculum_episodes.csv',
   'soccer_ppo_baseline_vs_soccer_ppo_curriculum_summary.json',
   'soccer_ppo_baseline_vs_soccer_ppo_curriculum_v2_episodes.csv',
   'soccer_ppo_baseline_vs_soccer_ppo_curriculum_v2_summary.json',
   'soccer_ppo_baseline_vs_soccer_ppo_curriculum_v3_episodes.csv',
   'soccer_ppo_baseline_vs_soccer_ppo_curriculum_v3_summary.json',
   'soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v2_episodes.csv',
   'soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v2_summary.json',
   'soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v3_episodes.csv',
   'soccer_ppo_curriculum_vs_soccer_ppo_curriculum_v3_summary.json']},
 'logs': {'path': '/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/logs',
  'file_count': 0,
  'examples': []}}

## Validate Exported Packages

Each candidate should import, instantiate with a real SoccerTwos env, and return actions for both players.

In [42]:
validation_rows = []
for module_name in CANDIDATE_AGENTS:
    package_dir = ctx.submissions_dir / module_name
    if not package_dir.exists():
        validation_rows.append({"agent": module_name, "exists": False, "valid": False, "message": "package folder missing"})
        continue
    try:
        validate_exported_package(ctx, module_name, rollout_steps=0)
        validation_rows.append({"agent": module_name, "exists": True, "valid": True, "message": "ok"})
    except Exception as exc:
        validation_rows.append({"agent": module_name, "exists": True, "valid": False, "message": "{}: {}".format(type(exc).__name__, exc)})

display(pd.DataFrame(validation_rows))

Using Unity base_port: 50051
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: soccer_ppo_baseline
Actions: {0: [2, 2, 2], 1: [1, 0, 2]}
{
  "actions": {
    "0": [
      2,
      2,
      2
    ],
    "1": [
      1,
      0,
      2
    ]
  },
  "module_name": "soccer_ppo_baseline",
  "package": {
    "exists": true,
    "file_count": 10,
    "files": [
      "README.md",
      "__init__.py",
      "__pycache__/__init__.cpython-38.pyc",
      "__pycache__/agent.cpython-38.pyc",
      "__pycache__/model.cpython-38.pyc",
      "agent.py",
      "checkpoint.pth",
      "metadata.json",
      "model.py",
      "requirements.txt"
    ],
    "has_agent_implementation": true,
    "missing_required_files": [],
    "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/soccer_ppo_baseline",
    "required_files_present": [
      "__init__.py"
    ]
  }
}
Using Unity base_port: 50053
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: soccer_ppo_shaped
Actions: {0: [1, 0, 0], 1: [0, 0, 1]}
{
  "actions": {
    "0": [
      1,
      0,
      0
    ],
    "1": [
      0,
      0,
      1
    ]
  },
  "module_name": "soccer_ppo_shaped",
  "package": {
    "exists": true,
    "file_count": 10,
    "files": [
      "README.md",
      "__init__.py",
      "__pycache__/__init__.cpython-38.pyc",
      "__pycache__/agent.cpython-38.pyc",
      "__pycache__/model.cpython-38.pyc",
      "agent.py",
      "checkpoint.pth",
      "metadata.json",
      "model.py",
      "requirements.txt"
    ],
    "has_agent_implementation": true,
    "missing_required_files": [],
    "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/soccer_ppo_shaped",
    "required_files_present": [
      "__init__.py"
    ]
  }
}
Using Unity base_port: 50054
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: soccer_ppo_curriculum
Actions: {0: [1, 0, 0], 1: [1, 0, 0]}
{
  "actions": {
    "0": [
      1,
      0,
      0
    ],
    "1": [
      1,
      0,
      0
    ]
  },
  "module_name": "soccer_ppo_curriculum",
  "package": {
    "exists": true,
    "file_count": 10,
    "files": [
      "README.md",
      "__init__.py",
      "__pycache__/__init__.cpython-38.pyc",
      "__pycache__/agent.cpython-38.pyc",
      "__pycache__/model.cpython-38.pyc",
      "agent.py",
      "checkpoint.pth",
      "metadata.json",
      "model.py",
      "requirements.txt"
    ],
    "has_agent_implementation": true,
    "missing_required_files": [],
    "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/soccer_ppo_curriculum",
    "required_files_present": [
      "__init__.py"
    ]
  }
}
Using Unity base_port: 50055
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: soccer_ppo_curriculum_v3
Actions: {0: [1, 0, 0], 1: [2, 2, 1]}
{
  "actions": {
    "0": [
      1,
      0,
      0
    ],
    "1": [
      2,
      2,
      1
    ]
  },
  "module_name": "soccer_ppo_curriculum_v3",
  "package": {
    "exists": true,
    "file_count": 10,
    "files": [
      "README.md",
      "__init__.py",
      "__pycache__/__init__.cpython-38.pyc",
      "__pycache__/agent.cpython-38.pyc",
      "__pycache__/model.cpython-38.pyc",
      "agent.py",
      "checkpoint.pth",
      "metadata.json",
      "model.py",
      "requirements.txt"
    ],
    "has_agent_implementation": true,
    "missing_required_files": [],
    "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/soccer_ppo_curriculum_v3",
    "required_files_present": [
      "__init__.py"
    ]
  }
}
Using Unity base_port: 50057
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: soccer_bc_imitation
Actions: {0: 9, 1: 9}
{
  "actions": {
    "0": 9,
    "1": 9
  },
  "module_name": "soccer_bc_imitation",
  "package": {
    "exists": true,
    "file_count": 10,
    "files": [
      "README.md",
      "__init__.py",
      "__pycache__/__init__.cpython-38.pyc",
      "__pycache__/agent.cpython-38.pyc",
      "__pycache__/model.cpython-38.pyc",
      "agent.py",
      "checkpoint.pth",
      "metadata.json",
      "model.py",
      "requirements.txt"
    ],
    "has_agent_implementation": true,
    "missing_required_files": [],
    "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/soccer_bc_imitation",
    "required_files_present": [
      "__init__.py"
    ]
  }
}

                      agent  exists  valid message
0       soccer_ppo_baseline    True   True      ok
1         soccer_ppo_shaped    True   True      ok
2     soccer_ppo_curriculum    True   True      ok
3  soccer_ppo_curriculum_v3    True   True      ok
4       soccer_bc_imitation    True   True      ok

## Final Evaluations

Keep this off until packages validate. For the report, run enough episodes to make the comparison meaningful.

In [43]:
if RUN_FINAL_EVALS:
    from soccer_twos_project.evaluation import evaluate, safe_label, write_outputs

    pairs = [
        ("soccer_ppo_baseline", SOURCE_AGENT),
        ("soccer_ppo_shaped", SOURCE_AGENT),
        ("soccer_ppo_curriculum", SOURCE_AGENT), # Compare v1 vs v3
    ]
    for agent1, agent2 in pairs:
        print("Evaluating", agent1, "vs", agent2)
        try:
            rows, summary = evaluate(agent1, agent2, episodes=10, base_port=None)
            write_outputs(rows, summary, ctx.dirs["evals"], safe_label(agent1, agent2))
            display(pd.DataFrame([summary]))
        except Exception as exc:
            print("Evaluation failed:", type(exc).__name__, exc)
else:
    print("Final evaluations skipped by RUN_FINAL_EVALS=False.")

Final evaluations skipped by RUN_FINAL_EVALS=False.

## Evaluation Table For Report

Load any summary JSON files already written under `artifacts/.../evals`.

In [44]:
evaluation_summaries(ctx)

,file,agent1,agent2,episodes,agent1_win_rate,agent1_reward_mean,agent2_reward_mean,draws
0,soccer_ppo_baseline_vs_soccer_ppo_curriculum_s...,soccer_ppo_baseline,soccer_ppo_curriculum,5,0.4,-0.48248,0.30576,0
1,soccer_ppo_baseline_vs_soccer_ppo_curriculum_v...,soccer_ppo_baseline,soccer_ppo_curriculum_v2,5,0.2,-1.22176,0.86960,0
2,soccer_ppo_baseline_vs_soccer_ppo_curriculum_v...,soccer_ppo_baseline,soccer_ppo_curriculum_v3,10,0.2,-1.20836,1.11404,0
3,soccer_ppo_curriculum_vs_soccer_ppo_curriculum...,soccer_ppo_curriculum,soccer_ppo_curriculum_v2,5,0.4,-0.42656,0.37000,0
4,soccer_ppo_curriculum_vs_soccer_ppo_curriculum...,soccer_ppo_curriculum,soccer_ppo_curriculum_v3,10,0.4,-0.42576,0.34072,0

## Rebuild Learning-Curve Plots

The report should include one curve per discussed agent and one direct comparison plot.

In [45]:
from soccer_twos_project.plotting import plot_results

try:
    plot_results(SimpleNamespace(
        artifact_root=str(ctx.artifact_root),
        ray_results=str(ctx.dirs["checkpoints"]),
        output_dir=str(ctx.dirs["plots"]),
        filter=None,
    ))
except Exception as exc:
    print("Plot rebuild skipped:", type(exc).__name__, exc)

Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_baseline__PPO_Soccer_2c827_00000_0_2026-04-23_08-51-41.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_baseline__PPO_Soccer_79595_00000_0_2026-04-23_08-32-21.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_baseline__PPO_Soccer_87dbd_00000_0_2026-04-23_08-18-26.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_curriculum__PPO_Soccer_8ce04_00000_0_2026-04-23_09-08-41.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_curriculum_v2__PPO_Soccer_dca3b_00000_0_2026-04-23_16-13-15.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_curriculum_v3__PPO_Soccer_0b1b1_00000_0_2026-04-23_18-09-05.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/soccer_ppo_shaped__PPO_Soccer_62ae7_00000_0_2026-04-23_09-00-21.png
Wrote /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots/learning_curve_comparison.png

## Create Final Submission Zip

The zip must extract to exactly one top-level folder named `TEAMNAME_AGENT` or your real team-specific replacement.

In [46]:
final_zip = None
if CREATE_FINAL_ZIP:
    try:
        final_zip = make_final_submission(ctx, SOURCE_AGENT, TEAM_AGENT_NAME)
        validate_zip_package(final_zip, expected_top_level=TEAM_AGENT_NAME)
    except Exception as exc:
        print("Final zip creation/validation failed:", type(exc).__name__, exc)
else:
    print("Final zip creation skipped by CREATE_FINAL_ZIP=False.")

final_zip

Final submission folder: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT
Final submission zip: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT.zip
{
  "file_count": 10,
  "missing_required_files": [],
  "top_level": "TEAMNAME_v3_AGENT",
  "zip_path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT.zip"
}
Using Unity base_port: 50058
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0

[INFO] Connected new brain: SoccerTwos?team=1

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1

[INFO] Connected new brain: SoccerTwos?team=0

INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0

Validated package: TEAMNAME_v3_AGENT
Actions: {0: [1, 0, 0], 1: [2, 2, 1]}

PosixPath('/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT.zip')

## Report Artifact Collection

Use this cell to collect paths and metadata for the writeup.

In [47]:
report_rows = []
for stage in ["ppo_baseline", "ppo_shaped", "ppo_curriculum", "ppo_curriculum_v3", "ppo_selfplay"]:
    report_rows.append(checkpoint_summary(ctx, stage))
display(pd.DataFrame(report_rows))
print("Plots directory:", ctx.dirs["plots"])
print("Evals directory:", ctx.dirs["evals"])

,stage,exists,checkpoint,experiment,stop,criterion,error
0,ppo_baseline,True,/coc/scratch/vchopra/rl_training/project/socce...,Soccer,{'timesteps_total': 2000000},policy performance baseline,NaN
1,ppo_shaped,True,/coc/scratch/vchopra/rl_training/project/socce...,Soccer,{'timesteps_total': 2000000},reward modification,NaN
2,ppo_curriculum,True,/coc/scratch/vchopra/rl_training/project/socce...,Soccer,{'timesteps_total': 2000000},curriculum policy performance,NaN
3,ppo_curriculum_v3,True,/coc/scratch/vchopra/rl_training/project/socce...,Soccer,{'timesteps_total': 30000000},curriculum policy performance (10M extended),NaN
4,ppo_selfplay,False,NaN,NaN,NaN,NaN,/coc/scratch/vchopra/rl_training/project/socce...

Plots directory: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/plots
Evals directory: /coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/evals

## Final Readiness Summary

This is a structural check. It does not prove the policy is strong; it proves the artifact is shaped like a valid submission.

In [48]:
summary = submission_readiness_summary(ctx, TEAM_AGENT_NAME, zip_path=final_zip)
if summary["ready"]:
    print("STRUCTURALLY READY: final submission artifact has the expected folder and zip structure.")
else:
    print("NOT READY YET: inspect the readiness summary above.")

{
  "file_count": 10,
  "missing_required_files": [],
  "top_level": "TEAMNAME_v3_AGENT",
  "zip_path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT.zip"
}
{
  "folder_missing_required": [],
  "package_dir": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT",
  "package_exists": true,
  "ready": true,
  "team_agent_name": "TEAMNAME_v3_AGENT",
  "zip_exists": true,
  "zip_manifest_ok": true,
  "zip_path": "/coc/scratch/vchopra/rl_training/project/soccer-twos-starter/artifacts/cs8803_soccer_twos/submissions/TEAMNAME_v3_AGENT.zip"
}
STRUCTURALLY READY: final submission artifact has the expected folder and zip structure.

## Key Takeaways

Submission finalization is separate from training. This notebook checks package importability, zip structure, plots, eval summaries, and report metadata.

## What To Run Next

Run `05_submission_smoke_test.ipynb` whenever you want a fast fresh smoke test of the training-export-zip-validation path.